In [1]:
!git clone https://github.com/Arijit1080/Licence-Plate-Detection-using-YOLO-V8.git

Cloning into 'Licence-Plate-Detection-using-YOLO-V8'...
remote: Enumerating objects: 117, done.
remote: Total 117 (delta 0), reused 0 (delta 0), pack-reused 117
Receiving objects: 100% (117/117), 183.86 KiB | 1012.00 KiB/s, done.
Resolving deltas: 100% (30/30), done.


In [2]:
cd /content/Licence-Plate-Detection-using-YOLO-V8

/content/Licence-Plate-Detection-using-YOLO-V8


In [19]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="xxx") #Put your API Key here
project = rf.workspace("snu-i6ovv").project("license-plate-detector-ogxxg")
dataset = project.version(1).download("yolov8")




loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics==8.0.134 is required but found version=8.0.3, to fix: `pip install ultralytics==8.0.134`


Extracting Dataset Version Zip to License-Plate-Detector-1 in yolov8:: 100%|██████████| 802/802 [00:00<00:00, 2172.06it/s]


In [4]:
!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.8/613.8 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.6/188.6 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 10.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.3 MB/s eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144554 sha256=34ec0adf003c4cd735558385dfefaffac6a773f6c5b0a7ff822465d27a72ca10
  Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime


In [22]:
!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/train.py model=yolov8n.pt data=/content/Licence-Plate-Detection-using-YOLO-V8/License-Plate-Detector-1/data.yaml epochs=100

yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/content/Licence-Plate-Detection-using-YOLO-V8/License-Plate-Detector-1/data.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weig

In [23]:
!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/runs/detect/train11/weights/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/demo1.mp4'

2023-09-02 10:13:15.778885: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-02 10:13:17.095302: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Ultralytics YOLOv8.0.3 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/631) /content/Licence-Plate-Detection-using-YOLO-V8/demo1.mp4: 416x640 1 LicensePlate, 55.1ms
video 1/1 (2/631) /content/Licence-Plate-Detection-using-YOLO-V8/demo1.mp4: 416x640 1 LicensePlate, 5.9ms
video 1/1 (3/631) /content/Licence-Plate-Detection-using-YOLO-V8/demo1.mp4: 416x640 1 LicensePlate, 5.9ms
video 1/1 (4/631) /content/Licence-Plate-Detection-using-YOLO-

In [24]:
!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/runs/detect/train11/weights/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/nm.jpeg'

2023-09-02 10:16:10.876094: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-02 10:16:12.318694: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Ultralytics YOLOv8.0.3 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
image 1/1 /content/Licence-Plate-Detection-using-YOLO-V8/nm.jpeg: 512x640 1 LicensePlate, 60.3ms
Speed: 0.5ms pre-process, 60.3ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/train13


In [1]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from ultralytics import YOLO
model=YOLO("yolov8n.pt")
model.predict(source="C:/Users/HP/Downloads/Project_1/video_path/input_1.mp4",save=True,imgsz=320,conf=0.5)

Ultralytics YOLOv8.0.3  Python-3.11.4 torch-2.3.1+cpu CPU
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
video 1/1 (1/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 91.0ms
video 1/1 (2/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 46.6ms
video 1/1 (3/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 45.9ms
video 1/1 (4/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 61.4ms
video 1/1 (5/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 53.2ms
video 1/1 (6/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 49.5ms
video 1/1 (7/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 52.4ms
video 1/1 (8/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 2 cars, 49.5ms
video 1/1 (9/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 2

[tensor([[1.07000e+02, 2.38000e+02, 9.44000e+02, 6.58000e+02, 9.44870e-01, 2.00000e+00],
         [8.00000e+01, 9.50000e+01, 2.59000e+02, 2.25000e+02, 8.50566e-01, 2.00000e+00]]),
 tensor([[1.16000e+02, 2.37000e+02, 9.36000e+02, 6.57000e+02, 9.42203e-01, 2.00000e+00],
         [7.70000e+01, 9.40000e+01, 2.64000e+02, 2.30000e+02, 8.64840e-01, 2.00000e+00]]),
 tensor([[1.18000e+02, 2.36000e+02, 9.24000e+02, 6.54000e+02, 9.38925e-01, 2.00000e+00],
         [7.30000e+01, 9.30000e+01, 2.67000e+02, 2.35000e+02, 8.50267e-01, 2.00000e+00]]),
 tensor([[1.17000e+02, 2.35000e+02, 9.14000e+02, 6.50000e+02, 9.32298e-01, 2.00000e+00],
         [6.90000e+01, 9.30000e+01, 2.66000e+02, 2.41000e+02, 8.43921e-01, 2.00000e+00]]),
 tensor([[1.15000e+02, 2.30000e+02, 9.01000e+02, 6.46000e+02, 8.92926e-01, 2.00000e+00],
         [5.90000e+01, 9.20000e+01, 2.63000e+02, 2.44000e+02, 8.18535e-01, 2.00000e+00]]),
 tensor([[1.10000e+02, 2.27000e+02, 8.86000e+02, 6.39000e+02, 8.33620e-01, 2.00000e+00],
         [4

In [4]:
from ultralytics import YOLO
model=YOLO("C:/Users/HP/Downloads/Project_1/runs/detect/train/weights/best.pt")
model.predict(source="C:/Users/HP/Downloads/Project_1/video_path/input_1.mp4",save=True,imgsz=320,conf=0.5)

Ultralytics YOLOv8.0.3  Python-3.11.4 torch-2.3.1+cpu CPU
Fusing layers... 
Model summary: 168 layers, 3006038 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 52.9ms
video 1/1 (2/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 48.3ms
video 1/1 (3/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 48.9ms
video 1/1 (4/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 46.5ms
video 1/1 (5/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 49.8ms
video 1/1 (6/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 57.5ms
video 1/1 (7/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 62.3ms
video 1/1 (8/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 45.1ms
video 1/1 (9/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 224x320 1 1, 50.6ms
video 1/1 (10/631

[tensor([], size=(0, 6)),
 tensor([], size=(0, 6)),
 tensor([[5.60000e+02, 5.23000e+02, 7.58000e+02, 5.86000e+02, 5.66408e-01, 1.00000e+00]]),
 tensor([[5.46000e+02, 5.22000e+02, 7.49000e+02, 5.86000e+02, 5.53455e-01, 1.00000e+00]]),
 tensor([[5.28000e+02, 5.20000e+02, 7.27000e+02, 5.83000e+02, 5.44734e-01, 1.00000e+00]]),
 tensor([[5.14000e+02, 5.11000e+02, 7.14000e+02, 5.78000e+02, 6.80754e-01, 1.00000e+00]]),
 tensor([[4.95000e+02, 5.05000e+02, 6.96000e+02, 5.71000e+02, 5.65924e-01, 1.00000e+00]]),
 tensor([[4.90000e+02, 4.99000e+02, 6.89000e+02, 5.66000e+02, 6.75626e-01, 1.00000e+00]]),
 tensor([[4.75000e+02, 4.96000e+02, 6.82000e+02, 5.66000e+02, 5.86635e-01, 1.00000e+00]]),
 tensor([[4.69000e+02, 4.92000e+02, 6.69000e+02, 5.66000e+02, 5.29394e-01, 1.00000e+00]]),
 tensor([], size=(0, 6)),
 tensor([[4.49000e+02, 4.86000e+02, 6.44000e+02, 5.42000e+02, 6.10412e-01, 1.00000e+00]]),
 tensor([], size=(0, 6)),
 tensor([[4.18000e+02, 4.79000e+02, 6.27000e+02, 5.40000e+02, 5.53735e-01, 1.

In [4]:
from ultralytics import YOLO

# Configure the tracking parameters and run the tracker
model = YOLO('yolov8n.pt')

results = model.track(source="testing/d.mp4",conf=0.3, iou=0.5, save=True, tracker="bytetrack.yaml")

AttributeError: 'YOLO' object has no attribute 'track'

In [5]:
!git clone https://github.com/nwojke/deep_sort.git

Cloning into 'deep_sort'...


In [6]:
%cd C:/Users/HP/Downloads/Project_1/deep_sort

C:\Users\HP\Downloads\Project_1\deep_sort


c:\Users\HP\Downloads\Project_1\myenv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [7]:
!pip install -r requirements.txt


In [9]:
from ultralytics import YOLO
import time
import torch
import cv2
import torch.backends.cudnn as cudnn
from PIL import Image
import colorsys
import numpy as np

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

results = model("C:/Users/HP/Downloads/Project_1/video_path/input_1.mp4", save=True)

class_names = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    probs = result.probs  # Class probabilities for classification outputs
    cls = boxes.cls.tolist()  # Convert tensor to list
    xyxy = boxes.xyxy
    xywh = boxes.xywh  # box with xywh format, (N, 4)
    conf = boxes.conf
    print(cls)
    for class_index in cls:
        class_name = class_names[int(class_index)]
        print("Class:", class_name)

Ultralytics YOLOv8.0.3  Python-3.11.4 torch-2.3.1+cpu CPU
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
video 1/1 (1/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 154.2ms
video 1/1 (2/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 106.3ms
video 1/1 (3/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 97.1ms
video 1/1 (4/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 134.6ms
video 1/1 (5/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 157.1ms
video 1/1 (6/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 101.4ms
video 1/1 (7/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 102.1ms
video 1/1 (8/631) C:\Users\HP\Downloads\Project_1\video_path\input_1.mp4: 416x640 2 cars, 104.2ms
video 1/1 (9/631) C:\Users\HP\Downloads\Project_1\video_path\input_1

AttributeError: 'Tensor' object has no attribute 'boxes'